---
title: "Task 2 - Juvenile Snowshoe Hares in Bonanza Creek Experimental Forest"
author: "Taylor Medina"
date: "11/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(here)
library(kableExtra)
library(lubridate)
library(plotly)
library(effsize)
library(broom)
```

## Juvenile Hare Investigation
```{r}
bonanza_hares <- read_csv(here("data", "bonanza_hares.csv"))

hare_trappings <- bonanza_hares %>% 
  mutate(date = mdy(date), # convert class of date column
         year = year(date)) %>% # splice out year
  group_by(year) %>% 
  summarize(trappings = n()) # get number of trappings per year
```

```{r}
hare_plot <- ggplot(data = hare_trappings,
                    aes(x = year, y = trappings)) +
  geom_point() +
  geom_line() +
  theme_classic() +
  labs(x = "year",
       y = "number of trappings")

ggplotly(hare_plot)
```

```{r}
hare_summary <- hare_trappings %>% 
  summarize(mean_trap = mean(trappings),
            sd_trap = sd(trappings),
            median_trap = median(trappings),
            max_trap = max(trappings),
            min_trap = min(trappings))

hare_summary %>% 
kable(col.names = c("mean",
                    "standard deviation",
                    "median",
                    "maximum",
                    "minimum"),
      caption = "Table 1: Statistical Summary of the number of trappings of Bonanza Hares from 1998-2012") %>% 
kable_classic(full_width = FALSE)
```

## Visualizing Juvenile Hare Weights
```{r}
hare_weights <- bonanza_hares %>% 
  group_by(grid, sex) %>% 
  summarize(mean_weight = mean(weight, na.rm = TRUE),
            sd_weight = sd(weight, na.rm = TRUE)) %>%
  mutate(grid = case_when( # replace short names of sites with full names
    grid == "bonbs" ~ "Bonanza Lowland",
    grid == "bonmat" ~ "Bonanza Mature",
    grid == "bonrip" ~ "Bonanza Riparian"))
 
x_axis <- c("female", "male", "NA") # define x-axis labels since they are strings

weight_plot <- ggplot(data = hare_weights,
                      aes(x = sex, y = mean_weight)) +
  geom_bar(stat = "identity", aes(fill = sex)) +
  geom_errorbar(data = hare_weights, 
                mapping = aes(x = sex, ymin = mean_weight - sd_weight, 
                              ymax = mean_weight + sd_weight, size = 0.2, width = 0.1)) +
  facet_wrap(~ grid) +
  theme_classic() +
  scale_y_continuous(expand = c(0,1)) +
  scale_x_discrete(labels = x_axis) + # manually define x-axis
  labs(x = "sex",
       y = "mass (g)",
       fill = "sex")
  

ggplotly(weight_plot)
```

## Statistics of Juvenile Hare Weights
```{r}
hare_stats <- bonanza_hares %>% 
  group_by(sex) %>% 
  summarize(mean_weight = mean(weight, na.rm = TRUE),
            sd_weight = sd(weight, na.rm = TRUE),
            sample_size = n()) %>% 
  filter(sex != "") # remove na row
  
hare_stats %>% 
  kable(col.names = c("sex",
                      "mean weight (g)",
                      "standard deviation (g)",
                      "sample size"),
        caption = "Table 2: Mean weights with standard deviation of Bonanza Hares") %>% 
  kable_classic(full_width = FALSE)
```

```{r, include = FALSE}
hare_stats_1 <- bonanza_hares %>% 
  group_by(sex) %>% 
  summarize(weight = weight) 

ggplot(data = hare_stats_1, aes(x = weight)) +
  geom_bar() + 
  facet_wrap(~ sex)

ggplot(data = hare_stats_1, aes(sample = weight)) +
  stat_qq() +
  stat_qq_line() +
  facet_wrap(~ sex)
```

```{r}
female_hares <- subset(hare_stats_1, sex == "f") %>% 
  na.omit() # omit na values

male_hares <- subset(hare_stats_1, sex == "m") %>% 
  na.omit() # omit na values

mean_diff = hare_stats$mean_weight[1] - hare_stats$mean_weight[2] # calculates difference in mean female vs. male height
cohen <- cohen.d(female_hares$weight, male_hares$weight) # performs a cohen D test to get the effect size
ttest <- t.test(female_hares$weight, male_hares$weight) # performs an unpaired 2-sample t-test

hare_analysis <- as.data.frame(t(c(mean_diff, cohen$estimate, ttest$p.value))) # puts results into a data frame

hare_analysis %>% 
  kable(col.names = c("means difference (g)",
                      "effect size",
                      "p-value"),
        caption = "Table 3: Statistical Analysis of Juvenile Hare Weights by Gender") %>% 
  footnote(number = c("The effect size was found using a Cohen D test", 
           "The p-value was found using a standard unpaired two-sample t-test")) %>% 
  kable_classic(full_width = FALSE)
```

## Juvenile Weight vs. Hind Foot Length
```{r}
hare_foot <- bonanza_hares %>% 
  select(sex, weight, hindft)

foot_plot <- ggplot(data = hare_foot, aes(x = weight, y = hindft)) +
  geom_point() +
  scale_x_continuous(expand = c(0,0)) +
  theme_classic() +
  labs(x = "weight (g)",
       y = "hind foot length (mm)") 
                      
ggplotly(foot_plot)                
```

```{r}
hare_lm <- lm(hindft ~ weight, data = hare_foot) # performs ordinary least squares regression

lm_plot <- ggplot(data = hare_foot, aes(x = weight, y = hindft)) +
  geom_point() +
  geom_smooth(method = "lm", color = "red", linewidth = 0.5, se = FALSE) +
  scale_x_continuous(expand = c(0,0)) +
  theme_classic() +
  labs(x = "weight (g)",
       y = "hind foot length (mm)")

ggplotly(lm_plot)
```

```{r}
lm_tidy <- tidy(hare_lm)

lm_glance <- glance(hare_lm) %>% 
  mutate(slope = lm_tidy$estimate[1], # extracts slope value from model fit
         intercept = lm_tidy$estimate[2], # extracts intercept value from model fit
         pearson = sqrt(adj.r.squared)) %>% # calculates Pearson Correlation
  select(slope, intercept, adj.r.squared, pearson)

lm_glance %>% 
  kable(col.names = c("slope",
                      "intercept",
                      "$R^2$",
                      "Pearson's correlation")) %>% 
  kable_classic(full_width = FALSE)
```



